services:
  app:
    build:
      context: .
      dockerfile: ${APP_ENV}/Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer:latest
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: ${DB_NAME}
      ADMINER_DEFAULT_USER: ${DB_USER}
      ADMINER_DEFAULT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  db_data: